spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username= postgres
#spring.datasource.password=admin
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=none